# Generated by Django 5.2.16 on 2026-07-12 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('message', 'Nova Mensagem'), ('booking_request', 'Solicitação de Agendamento'), ('booking_accepted', 'Agendamento Aceito'), ('booking_declined', 'Agendamento Recusado'), ('contract', 'Novo Contrato'), ('contract_signed', 'Contrato Assinado'), ('payment_received', 'Pagamento Recebido'), ('payment_failed', 'Pagamento Falhou'), ('review', 'Nova Avaliação'), ('follow', 'Novo Seguidor'), ('system', 'Sistema')], default='system', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(max_length=1000, verbose_name='Mensagem')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dados Extras')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Enviado')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Enviado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
