# Generated by Django 5.2.16 on 2026-07-12 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('work_type', models.CharField(choices=[('video', 'Vídeo'), ('photo', 'Foto'), ('mixed', 'Misto')], default='video', max_length=10, verbose_name='Tipo')),
                ('file', models.FileField(blank=True, null=True, upload_to='works/files/', verbose_name='Arquivo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='works/thumbnails/', verbose_name='Thumbnail')),
                ('external_url', models.URLField(blank=True, verbose_name='URL Externa')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do Cliente')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('equipment_used', models.TextField(blank=True, verbose_name='Equipamentos Utilizados')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Curtidas')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='portfolio.category', verbose_name='Categoria')),
                ('videomaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='Videomaker')),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='works/media/', verbose_name='Arquivo')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], default='image', max_length=10, verbose_name='Tipo')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolio.work', verbose_name='Trabalho')),
            ],
            options={
                'verbose_name': 'Mídia do Trabalho',
                'verbose_name_plural': 'Mídias do Trabalho',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='De 1 a 5', verbose_name='Nota')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Comentário')),
                ('response', models.TextField(blank=True, max_length=1000, verbose_name='Resposta')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('videomaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Videomaker')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='portfolio.work', verbose_name='Trabalho')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
                'unique_together': {('reviewer', 'videomaker', 'work')},
            },
        ),
    ]
