# Generated by Django 5.2.16 on 2026-07-12 16:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('profile_type', models.CharField(choices=[('videomaker', 'Videomaker'), ('client', 'Cliente'), ('both', 'Ambos')], default='both', max_length=10, verbose_name='Tipo de Perfil')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='CPF: XXX.XXX.XXX-XX ou CNPJ: XX.XXX.XXX/XXXX-XX', max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografia')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('youtube', models.CharField(blank=True, max_length=100, verbose_name='YouTube')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('is_videomaker', models.BooleanField(default=False, verbose_name='É Videomaker')),
                ('is_client', models.BooleanField(default=False, verbose_name='É Cliente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'Pessoa Física'), ('company', 'Empresa'), ('agency', 'Agência')], default='individual', max_length=20, verbose_name='Tipo de Cliente')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Nome da Empresa')),
                ('company_cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ da Empresa')),
                ('total_contracts', models.IntegerField(default=0, verbose_name='Total de Contratos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil Cliente',
                'verbose_name_plural': 'Perfis Clientes',
                'ordering': ['-total_contracts'],
            },
        ),
        migrations.CreateModel(
            name='VideomakerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, choices=[('wedding', 'Casamento'), ('corporate', 'Corporativo'), ('event', 'Eventos'), ('music_video', 'Clipe Musical'), ('documentary', 'Documentário'), ('commercial', 'Comercial'), ('social_media', 'Redes Sociais'), ('other', 'Outro')], max_length=20, verbose_name='Especialidade Principal')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado por hora de trabalho', max_digits=8, null=True, verbose_name='Valor Hora')),
                ('day_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado por dia de trabalho', max_digits=8, null=True, verbose_name='Valor Diária')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('travel_radius', models.IntegerField(default=50, help_text='Distância máxima que está disposto a viajar', verbose_name='Raio de Atendimento (km)')),
                ('total_jobs', models.IntegerField(default=0, verbose_name='Total de Trabalhos')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Avaliação Média')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='Total de Avaliações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='videomaker_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil Videomaker',
                'verbose_name_plural': 'Perfis Videomakers',
                'ordering': ['-average_rating', '-total_jobs'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Seguindo')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Seguidor')),
            ],
            options={
                'verbose_name': 'Seguidor',
                'verbose_name_plural': 'Seguidores',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'followed')},
            },
        ),
        migrations.CreateModel(
            name='VideomakerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Básico'), (3, 'Intermediário'), (4, 'Avançado'), (5, 'Especialista')], default=3, verbose_name='Nível de Experiência')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videomakers', to='accounts.skill', verbose_name='Habilidade')),
                ('videomaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.videomakerprofile', verbose_name='Videomaker')),
            ],
            options={
                'verbose_name': 'Habilidade do Videomaker',
                'verbose_name_plural': 'Habilidades dos Videomakers',
                'unique_together': {('videomaker', 'skill')},
            },
        ),
    ]
