# Generated by Django 6.0.7 on 2026-07-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token de Reset'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Token'),
        ),
    ]
