# Generated by Django 5.2.16 on 2026-07-12 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=20, verbose_name='Tipo de Evento')),
                ('description', models.TextField(verbose_name='Descrição do Evento')),
                ('preferred_date', models.DateField(verbose_name='Data Preferida')),
                ('preferred_time', models.TimeField(verbose_name='Horário Preferido')),
                ('estimated_duration', models.DurationField(verbose_name='Duração Estimada')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita'), ('declined', 'Recusada'), ('expired', 'Expirada')], default='pending', max_length=10, verbose_name='Status')),
                ('decline_reason', models.TextField(blank=True, verbose_name='Motivo da Recusa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('videomaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Videomaker')),
            ],
            options={
                'verbose_name': 'Solicitação de Agendamento',
                'verbose_name_plural': 'Solicitações de Agendamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Descrição')),
                ('event_type', models.CharField(choices=[('wedding', 'Casamento'), ('corporate', 'Corporativo'), ('event', 'Evento'), ('shoot', 'Gravação'), ('editing', 'Edição'), ('meeting', 'Reunião'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo')),
                ('start_datetime', models.DateTimeField(verbose_name='Data/Hora Início')),
                ('end_datetime', models.DateTimeField(verbose_name='Data/Hora Fim')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_events', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('videomaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videomaker_events', to=settings.AUTH_USER_MODEL, verbose_name='Videomaker')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(verbose_name='Horário Início')),
                ('end_time', models.TimeField(verbose_name='Horário Fim')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('videomaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL, verbose_name='Videomaker')),
            ],
            options={
                'verbose_name': 'Disponibilidade',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('videomaker', 'day_of_week')},
            },
        ),
    ]
