# Generated by Django 5.2.16 on 2026-07-12 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número do Contrato')),
                ('service_type', models.CharField(choices=[('wedding', 'Casamento'), ('corporate', 'Corporativo'), ('event', 'Evento'), ('music_video', 'Clipe Musical'), ('commercial', 'Comercial'), ('social_media', 'Redes Sociais'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo de Serviço')),
                ('service_description', models.TextField(verbose_name='Descrição do Serviço')),
                ('event_date', models.DateField(verbose_name='Data do Evento')),
                ('delivery_date', models.DateField(verbose_name='Data de Entrega')),
                ('location', models.CharField(max_length=200, verbose_name='Local do Evento')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('boleto', 'Boleto'), ('bank_transfer', 'Transferência Bancária')], default='pix', max_length=20, verbose_name='Método de Pagamento')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_signature', 'Aguardando Assinatura'), ('signed', 'Assinado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='draft', max_length=20, verbose_name='Status')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/pdfs/', verbose_name='PDF do Contrato')),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash SHA-256')),
                ('client_signed', models.BooleanField(default=False, verbose_name='Assinado pelo Cliente')),
                ('videomaker_signed', models.BooleanField(default=False, verbose_name='Assinado pelo Videomaker')),
                ('client_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data Assinatura Cliente')),
                ('videomaker_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data Assinatura Videomaker')),
                ('additional_clauses', models.TextField(blank=True, verbose_name='Cláusulas Adicionais')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('videomaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_videomaker', to=settings.AUTH_USER_MODEL, verbose_name='Videomaker')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('scope', 'Escopo do Serviço'), ('payment', 'Condições de Pagamento'), ('delivery', 'Prazo de Entrega'), ('cancellation', 'Cancelamento'), ('confidentiality', 'Sigilo'), ('copyright', 'Direitos Autorais'), ('liability', 'Responsabilidade'), ('revision', 'Revisões'), ('force_majeure', 'Força Maior'), ('jurisdiction', 'Foro'), ('additional', 'Adicional')], max_length=20, verbose_name='Tipo da Cláusula')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Cláusula do Contrato',
                'verbose_name_plural': 'Cláusulas do Contrato',
                'ordering': ['order'],
                'unique_together': {('contract', 'clause_type')},
            },
        ),
    ]
